# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c0953f9a713f8c59c13b75d98c81ecc77a1e19c878d2c7fad50e07f29b6fa0252d438049109645b571ff096d3bca78c019ff0543a4964eafb599ba19128d21c

test:
  secret_key_base: fe212c0ffc98cefbcb8ac30f7b797b48cf005903c85829c6f7c81d5b4ddedf30f21dad9c2f5bc459d8c72c82d308393e127910be6e7f5a020120f4172313c990

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
